name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker login --username ${{ secrets.USERNAME }} --password ${{ secrets.GH_PAT}} ghcr.io
        docker build . --tag ghcr.io/ivannanavrotska/my-code-testing-image:latest
        docker push ghcr.io/ivannanavrotska/my-code-testing-image:latest
    - name: Docker run
      run: |
        docker run --name my-container -d ghcr.io/ivannanavrotska/my-code-testing-image:latest
